language: php
dist: xenial
os: linux

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - nightly

jobs:
  allow_failures:
    - php: nightly
  fast_finish: true

before_script:
  - composer update -n --prefer-dist

script:
  - phpdbg -qrr vendor/bin/phpunit --coverage-text --coverage-clover build/logs/clover.xml
  - PHP_CS_FIXER_IGNORE_ENV=1 php vendor/bin/php-cs-fixer --diff --dry-run -v fix
  - vendor/bin/psalm

after_script:
  - curl -OL https://github.com/php-coveralls/php-coveralls/releases/download/v1.0.0/coveralls.phar
  - chmod +x coveralls.phar
  - ./coveralls.phar -v

cache:
  directories:
    - $HOME/.composer/cache/files
    - $HOME/.php-cs-fixer
